name: "Build&Deploy movai-shell images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  # on:
  #   release:
  #     types: [released]
jobs:
  movai-shell:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: ./Dockerfile
      docker_image: registry.cloud.mov.ai/devops/movai-shell
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
